### ISSUE TITLE
something to limit memory

### ISSUE THREAD

**Issue by c-cube** [danr/hbmc#4]
for several times now, hbmc ate all my ram in a few dozen seconds, so much that it even froze the computer and forced me to restart

**Comment by danr** [comment]
You can use `ulimit` for that. For instance, to limit later processes in a shell to have 7GB of memory:

    ulimit -Sv 7000000

Hope this helps!

**Comment by c-cube** [comment]
Ah, thanks a lot! I was trying with `ulimit -m 7000000` but it's just ignored on my OS.
